/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.nikitakoselev.upskilling.java.java8;

import java.util.Arrays;
import java.util.List;
import java.util.function.Predicate;

public class Java8Features {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Java8Features().getGreeting());
    }

    public String lambdaUsage() {
        SaySomething ss = () -> "hey Bro";
        return ss.sayIt();
    }

    public int streamUsage(List<String> names, Predicate<String> longerThan3) {
        return (int) names.stream().filter(longerThan3).count();
    }
}
